#!/bin/bash

deleteCmd(){
	
	cd /usr/local/bin
	sudo rm mkfile
	echo "mkfile was deleted from the /usr/local/bin directory"
	
	cd /usr/bin
	sudo rm makemake
	echo "makemake command has been removed."
	
	return
}

deleteCmd
